# Generated by Django 5.2.7 on 2025-10-25 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('time_to_complete__lte', 120)), name='time_to_complete_lte_120'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('periodicity__gte', 1), ('periodicity__lte', 7)), name='periodicity_range_1_7'),
        ),
    ]
